// Wortliste. Bei JEDER Aenderung WORDLIST_VERSION erhoehen, sonst sehen Handys mit
// altem und neuem Stand unterschiedliche Woerter (der Pruefcode zeigt das dann an).
//
// special: true = Themen-Kategorie (Anime, Filme, ...). Nur Begriffe, die auch
// Leute kennen, die sich nicht fuer das Thema interessieren.
export const WORDLIST_VERSION = 4;

export const CATEGORIES = [
  {
    id: "essen",
    name: "Essen & Trinken",
    words: [
      "Pizza", "Lasagne", "Brezel", "Sushi", "Pfannkuchen", "Currywurst", "Schnitzel",
      "Apfelstrudel", "Döner", "Burger", "Pommes", "Spaghetti", "Kartoffelsalat",
      "Leberkäse", "Weißwurst", "Käsespätzle", "Gulasch", "Suppe", "Salat", "Toast",
      "Croissant", "Müsli", "Joghurt", "Honig", "Marmelade", "Ei", "Käse", "Butter",
      "Brot", "Banane", "Erdbeere", "Wassermelone", "Ananas", "Kirsche", "Zitrone",
      "Avocado", "Karotte", "Gurke", "Tomate", "Zwiebel", "Knoblauch", "Pilz",
      "Popcorn", "Chips", "Schokolade", "Gummibärchen", "Eis", "Kuchen", "Torte",
      "Donut", "Muffin", "Keks", "Waffel", "Kaffee", "Tee", "Kakao", "Bier", "Wein",
      "Sekt", "Limonade", "Milch", "Cocktail", "Taco", "Hotdog", "Steak", "Lachs",
      "Tiramisu", "Pudding", "Rührei", "Frikadelle",
    ],
  },
  {
    id: "orte",
    name: "Orte",
    words: [
      "Flughafen", "Zahnarztpraxis", "Schwimmbad", "Bibliothek", "Friedhof", "Kino",
      "Baumarkt", "Bahnhof", "Krankenhaus", "Schule", "Universität", "Kirche",
      "Museum", "Zoo", "Freizeitpark", "Strand", "Campingplatz", "Hotel", "Restaurant",
      "Bäckerei", "Supermarkt", "Tankstelle", "Gefängnis", "Polizeiwache",
      "Feuerwache", "Rathaus", "Bank", "Fitnessstudio", "Stadion", "Disco", "Kneipe",
      "Oktoberfest", "Weihnachtsmarkt", "Casino", "Zirkus", "Bauernhof", "Burg",
      "Leuchtturm", "Wüste", "Dschungel", "Insel", "Höhle", "Keller", "Dachboden",
      "Garage", "Badezimmer", "Küche", "Aufzug", "Parkhaus", "Spielplatz",
      "Friseursalon", "Autobahn", "Wartezimmer", "Waschsalon", "Sauna", "Skigebiet",
      "Tattoostudio", "Flohmarkt", "Festival", "Theater", "Hochzeit", "Klassenzimmer",
    ],
  },
  {
    id: "tiere",
    name: "Tiere",
    words: [
      "Giraffe", "Pinguin", "Eichhörnchen", "Krokodil", "Qualle", "Fledermaus", "Kamel",
      "Papagei", "Elefant", "Löwe", "Tiger", "Zebra", "Nilpferd", "Nashorn", "Affe",
      "Gorilla", "Känguru", "Koala", "Panda", "Eisbär", "Wolf", "Fuchs", "Hase", "Igel",
      "Maulwurf", "Biber", "Waschbär", "Hirsch", "Wildschwein", "Kuh", "Schwein",
      "Schaf", "Ziege", "Pferd", "Esel", "Huhn", "Ente", "Schwan", "Eule", "Adler",
      "Flamingo", "Storch", "Taube", "Hai", "Wal", "Delfin", "Oktopus", "Seepferdchen",
      "Schildkröte", "Frosch", "Schlange", "Chamäleon", "Spinne", "Biene", "Ameise",
      "Schmetterling", "Marienkäfer", "Mücke", "Schnecke", "Hamster",
      "Meerschweinchen", "Katze", "Hund", "Goldfisch", "Faultier", "Lama",
    ],
  },
  {
    id: "berufe",
    name: "Berufe",
    words: [
      "Feuerwehrmann", "Pilot", "Friseur", "Bäcker", "Richter", "Hebamme", "Zauberer",
      "Astronaut", "Arzt", "Zahnarzt", "Krankenpfleger", "Tierarzt", "Polizist",
      "Lehrer", "Koch", "Kellner", "Barkeeper", "Busfahrer", "Taxifahrer", "Postbote",
      "Müllmann", "Bauarbeiter", "Elektriker", "Klempner", "Schreiner", "Gärtner",
      "Bauer", "Metzger", "Fischer", "Anwalt", "Detektiv", "Soldat", "Pfarrer",
      "Politiker", "Bürgermeister", "Journalist", "Fotograf", "Schauspieler", "Sänger",
      "DJ", "Clown", "Model", "Influencer", "Programmierer", "Architekt",
      "Wissenschaftler", "Kassierer", "Türsteher", "Bademeister", "Skilehrer",
      "Tätowierer", "Mechaniker", "Schornsteinfeger", "Hausmeister", "Flugbegleiter",
      "Kapitän", "Babysitter", "Dirigent", "Chirurg", "Psychologe",
    ],
  },
  {
    id: "gegenstaende",
    name: "Gegenstände",
    words: [
      "Regenschirm", "Zahnbürste", "Staubsauger", "Kompass", "Hängematte",
      "Taschenlampe", "Schlüssel", "Kerze", "Handy", "Laptop", "Fernbedienung",
      "Kopfhörer", "Brille", "Wecker", "Spiegel", "Kamm", "Föhn", "Rasierer",
      "Handtuch", "Seife", "Kissen", "Matratze", "Stuhl", "Sofa", "Lampe",
      "Kühlschrank", "Mikrowelle", "Toaster", "Waschmaschine", "Bügeleisen", "Pfanne",
      "Topf", "Messer", "Gabel", "Löffel", "Teller", "Tasse", "Flasche",
      "Korkenzieher", "Schere", "Kleber", "Bleistift", "Radiergummi", "Lineal",
      "Rucksack", "Koffer", "Geldbeutel", "Kreditkarte", "Feuerzeug", "Hammer",
      "Schraubenzieher", "Bohrmaschine", "Leiter", "Besen", "Eimer", "Gießkanne",
      "Teddybär", "Luftballon", "Würfel", "Fernseher", "Kamera", "Nagel", "Sanduhr",
      "Lupe", "Briefmarke", "Kalender", "Klopapier", "Zahnpasta",
    ],
  },
  {
    id: "freizeit",
    name: "Sport & Freizeit",
    words: [
      "Fußball", "Basketball", "Tennis", "Tischtennis", "Volleyball", "Handball",
      "Eishockey", "Golf", "Boxen", "Judo", "Karate", "Yoga", "Joggen", "Schwimmen",
      "Tauchen", "Surfen", "Segeln", "Rudern", "Skifahren", "Snowboard",
      "Schlittschuh", "Schlitten", "Klettern", "Wandern", "Radfahren", "Skateboard",
      "Bowling", "Billard", "Darts", "Minigolf", "Schach", "Poker", "Karaoke", "Tanzen",
      "Angeln", "Grillen", "Picknick", "Camping", "Trampolin", "Achterbahn",
      "Riesenrad", "Paintball", "Lasertag", "Escape Room", "Formel 1",
      "Marathon", "Olympia", "Reiten", "Fechten", "Bogenschießen",
      "Fallschirmspringen", "Bungee-Jumping", "Stricken", "Puzzle", "Sudoku",
    ],
  },
  {
    id: "natur",
    name: "Natur & Wetter",
    words: [
      "Regenbogen", "Gewitter", "Blitz", "Schnee", "Hagel", "Nebel", "Sturm",
      "Tornado", "Tsunami", "Erdbeben", "Lawine", "Sonne", "Mond", "Stern", "Komet",
      "Sonnenfinsternis", "Wolke", "Pfütze", "Eiszapfen", "Schneemann", "Berg",
      "Fluss", "See", "Meer", "Wasserfall", "Gletscher", "Wald", "Wiese", "Sumpf",
      "Vulkan", "Sand", "Kaktus", "Palme", "Tanne", "Eiche", "Rose", "Sonnenblume",
      "Tulpe", "Löwenzahn", "Moos", "Kastanie", "Tannenzapfen", "Muschel", "Koralle",
      "Lagerfeuer", "Nordlicht", "Sonnenuntergang",
    ],
  },
  {
    id: "koerper",
    name: "Körper & Gesundheit",
    words: [
      "Nase", "Ohr", "Auge", "Zunge", "Zahn", "Bart", "Glatze", "Augenbraue", "Knie",
      "Ellbogen", "Zeh", "Daumen", "Bauchnabel", "Muskel", "Herz", "Gehirn", "Lunge",
      "Magen", "Knochen", "Blut", "Fingernagel", "Sommersprosse", "Pickel", "Tattoo",
      "Piercing", "Pflaster", "Spritze", "Gips", "Rollstuhl", "Krücke", "Schnupfen",
      "Schluckauf", "Muskelkater", "Sonnenbrand", "Gänsehaut", "Zahnspange",
    ],
  },
  {
    id: "fahrzeuge",
    name: "Fahrzeuge",
    words: [
      "Auto", "Bus", "LKW", "Traktor", "Motorrad", "Roller", "Fahrrad", "Tandem",
      "E-Scooter", "Straßenbahn", "U-Bahn", "Zug", "Taxi", "Krankenwagen",
      "Feuerwehrauto", "Polizeiauto", "Müllauto", "Bagger", "Kran", "Gabelstapler",
      "Wohnmobil", "Cabrio", "Limousine", "Rennwagen", "Panzer", "Flugzeug",
      "Hubschrauber", "Heißluftballon", "Zeppelin", "Rakete", "Ufo", "Segelboot",
      "Kreuzfahrtschiff", "U-Boot", "Jetski", "Seilbahn", "Kutsche", "Einrad",
      "Kinderwagen", "Einkaufswagen", "Tretboot",
    ],
  },
  {
    id: "kleidung",
    name: "Kleidung",
    words: [
      "Jeans", "Jogginghose", "Lederhose", "Dirndl", "Kleid", "Rock", "Bluse", "Hemd",
      "T-Shirt", "Pullover", "Hoodie", "Jacke", "Mantel", "Anzug", "Krawatte", "Fliege",
      "Gürtel", "Hosenträger", "Socke", "Strumpfhose", "Unterhose", "Bikini",
      "Badehose", "Schlafanzug", "Bademantel", "Mütze", "Hut", "Schal", "Handschuh",
      "Sonnenbrille", "Sneaker", "Gummistiefel", "Flip-Flop", "High Heels",
      "Hausschuh", "Uniform", "Kostüm", "Brautkleid", "Trikot", "Halskette",
      "Ohrring", "Ring", "Armbanduhr",
    ],
  },
  {
    id: "party",
    name: "Party",
    words: [
      "Shot", "Kater", "Afterparty", "Tanzfläche", "Jägermeister", "Bierpong",
      "Flunkyball", "Trinkspiel", "Wahrheit oder Pflicht", "Flaschendrehen",
      "Vorglühen", "Filmriss", "Konfetti", "Nebelmaschine", "Discokugel", "Polonaise",
      "Partyhut", "Wunderkerze", "Feuerwerk", "Silvester", "Junggesellenabschied",
      "Hausparty", "WG-Party", "Mottoparty", "Aperol Spritz", "Mojito", "Tequila",
      "Wodka", "Sangria", "Bowle", "Eiswürfel", "Strohhalm", "Pfandflasche", "Kiosk",
      "Mitternachtsdöner", "Heimweg", "Kopfschmerztablette", "Selfie", "Playlist",
      "Lärmbeschwerde", "Limbo", "Tanzbattle", "Gästeliste", "Garderobe",
      "Geburtstagskuchen", "Luftschlange", "Stroboskop", "Abschleppen",
    ],
  },
  {
    id: "fabel",
    name: "Fabelwesen & Märchen",
    words: [
      "Einhorn", "Drache", "Vampir", "Werwolf", "Zombie", "Hexe", "Geist",
      "Meerjungfrau", "Troll", "Zwerg", "Elfe", "Fee", "Kobold", "Riese", "Phönix",
      "Pegasus", "Zentaur", "Medusa", "Yeti", "Nessie", "Frankenstein", "Mumie",
      "Rotkäppchen", "Schneewittchen", "Aschenputtel", "Dornröschen", "Rapunzel",
      "Hänsel und Gretel", "Rumpelstilzchen", "Froschkönig", "Der gestiefelte Kater",
      "Pinocchio", "Peter Pan", "Aladdin", "Flaschengeist", "Wunderlampe",
      "Lebkuchenhaus", "Zauberspiegel", "Zauberstab", "Hexenbesen", "Ritter",
      "Prinzessin", "Osterhase", "Weihnachtsmann", "Zahnfee", "Sandmännchen",
      "Christkind",
    ],
  },
  {
    id: "laender",
    name: "Länder",
    words: [
      "Deutschland", "Österreich", "Schweiz", "Italien", "Frankreich", "Spanien",
      "Portugal", "Griechenland", "Türkei", "Großbritannien", "Irland", "Niederlande",
      "Belgien", "Dänemark", "Schweden", "Norwegen", "Finnland", "Island", "Polen",
      "Tschechien", "Kroatien", "Ungarn", "Russland", "Ukraine", "USA", "Kanada",
      "Mexiko", "Brasilien", "Argentinien", "Kuba", "Jamaika", "Ägypten", "Marokko",
      "Südafrika", "Kenia", "China", "Japan", "Südkorea", "Nordkorea", "Indien",
      "Thailand", "Vietnam", "Indonesien", "Australien", "Neuseeland",
      "Vereinigte Arabische Emirate", "Saudi-Arabien", "Israel", "Peru", "Chile",
      "Kolumbien", "Vatikanstadt",
    ],
  },
  {
    id: "anime",
    name: "Anime & Manga",
    special: true,
    words: [
      "Naruto", "One Piece", "Dragon Ball", "Pokémon", "Pikachu", "Son Goku", "Ruffy",
      "Sailor Moon", "Attack on Titan", "Death Note", "Demon Slayer",
      "My Hero Academia", "Jujutsu Kaisen", "One Punch Man", "Spy x Family",
      "Tokyo Ghoul", "Bleach", "Yu-Gi-Oh!", "Digimon", "Detektiv Conan", "Heidi",
      "Chihiros Reise", "Totoro", "Studio Ghibli", "Sasuke", "Kakashi", "Vegeta",
      "Nezuko", "Kamehameha", "Rasengan", "Teufelsfrucht", "Sharingan", "Hokage",
      "Manga", "Cosplay", "Pokéball", "Glumanda", "Team Rocket", "Titan",
      "Super Saiyajin",
    ],
  },
  {
    id: "filme",
    name: "Filme & Serien",
    special: true,
    words: [
      "Harry Potter", "Star Wars", "Herr der Ringe", "Titanic", "König der Löwen",
      "Findet Nemo", "Shrek", "Toy Story", "Die Eiskönigin", "Avatar",
      "Jurassic Park", "Fluch der Karibik", "James Bond", "Matrix",
      "Avengers", "Barbie", "Minions", "Ice Age", "Cars",
      "Top Gun", "Rocky", "Der Pate", "Breaking Bad", "Game of Thrones",
      "Stranger Things", "Haus des Geldes", "Squid Game", "Friends", "Die Simpsons",
      "SpongeBob", "Tatort", "Dark", "How I Met Your Mother", "Big Bang Theory",
      "Sherlock", "Wednesday", "The Walking Dead", "Peaky Blinders",
      "Fack ju Göhte", "Der Schuh des Manitu", "Kevin allein zu Haus", "Mr. Bean",
      "Indiana Jones", "Zurück in die Zukunft", "Ghostbusters", "Hangover",
    ],
  },
  {
    id: "games",
    name: "Videospiele",
    special: true,
    words: [
      "Minecraft", "Fortnite", "Mario Kart", "Super Mario", "Zelda", "Tetris",
      "Pac-Man", "Sonic", "GTA", "FIFA", "Call of Duty", "Counter-Strike",
      "League of Legends", "Among Us", "Rocket League", "Die Sims", "Animal Crossing",
      "Wii Sports", "Just Dance", "SingStar", "Clash of Clans", "Candy Crush",
      "Subway Surfers", "Angry Birds", "Flappy Bird", "Overwatch", "Valorant",
      "World of Warcraft", "Skyrim", "The Witcher", "Red Dead Redemption",
      "Assassin's Creed", "Donkey Kong", "Kirby", "Smash Bros", "Crash Bandicoot",
      "Guitar Hero", "Mario Party", "Brawl Stars", "Roblox", "PlayStation",
      "Nintendo Switch", "Game Boy", "Tamagotchi",
    ],
  },
  {
    id: "marken",
    name: "Marken",
    special: true,
    words: [
      "Coca-Cola", "McDonald's", "IKEA", "Apple", "Nike", "Adidas", "Lego", "Haribo",
      "Nutella", "Red Bull", "Starbucks", "Amazon", "Netflix", "Spotify", "Google",
      "Instagram", "TikTok", "WhatsApp", "YouTube", "Tesla", "BMW", "Mercedes",
      "Porsche", "Volkswagen", "Ferrari", "Playmobil", "Aldi", "Lidl", "dm", "H&M",
      "Zara", "Deutsche Bahn", "Lufthansa", "Disney", "Kinder Überraschung", "Milka",
      "Burger King", "Nivea", "Capri-Sonne", "Maggi",
    ],
  },
  {
    id: "promis",
    name: "Promis",
    special: true,
    words: [
      "Angela Merkel", "Olaf Scholz", "Barack Obama", "Donald Trump", "Elon Musk",
      "Taylor Swift", "Beyoncé", "Rihanna", "Michael Jackson", "Elvis Presley",
      "Madonna", "Lady Gaga", "Ed Sheeran", "Justin Bieber", "Kim Kardashian",
      "Cristiano Ronaldo", "Lionel Messi", "Thomas Müller", "Manuel Neuer",
      "Michael Schumacher", "Dirk Nowitzki", "Boris Becker", "Helene Fischer",
      "Heidi Klum", "Dieter Bohlen", "Stefan Raab", "Thomas Gottschalk",
      "Jan Böhmermann", "Joko und Klaas", "Til Schweiger", "Arnold Schwarzenegger",
      "Leonardo DiCaprio", "Brad Pitt", "Tom Cruise", "Dwayne Johnson", "MrBeast",
      "Albert Einstein", "Queen Elizabeth", "Mark Zuckerberg", "Bill Gates",
      "Steve Jobs", "Eminem", "Snoop Dogg", "Shakira", "Adele", "Billie Eilish",
      "Bushido", "Apache 207", "Karl Lagerfeld", "Marilyn Monroe", "Mozart",
      "Goethe", "Kleopatra", "Napoleon",
      // Schauspieler
      "Johnny Depp", "Tom Hanks", "Will Smith", "Keanu Reeves", "Scarlett Johansson",
      "Angelina Jolie", "Jennifer Aniston", "Margot Robbie", "Zendaya",
      "Timothée Chalamet", "Ryan Gosling", "Ryan Reynolds", "Morgan Freeman",
      "Jackie Chan", "Robert Downey Jr.", "Emma Watson", "Daniel Radcliffe",
      "Matthias Schweighöfer", "Elyas M'Barek", "Jim Carrey", "Adam Sandler",
      "Denzel Washington", "Meryl Streep", "Nicolas Cage", "Vin Diesel",
    ],
  },
  {
    id: "helden",
    name: "Superhelden & Schurken",
    special: true,
    words: [
      "Superman", "Batman", "Spider-Man", "Iron Man", "Captain America", "Thor", "Hulk",
      "Black Widow", "Wonder Woman", "Aquaman", "Flash", "Wolverine", "Deadpool",
      "Black Panther", "Doctor Strange", "Ant-Man", "Groot", "Catwoman", "Robin",
      "Joker", "Thanos", "Loki", "Venom", "Magneto", "Harley Quinn", "Darth Vader",
      "Voldemort", "Lex Luthor", "Bane", "Riddler", "Scar", "Ursula", "Cruella",
      "Captain Hook", "Grinch", "Sauron", "Gollum", "Freddy Krueger", "Chucky",
      "Pennywise", "Hannibal Lecter", "Dracula", "Kryptonit", "Batmobil",
      "Bat-Signal", "Umhang", "Superkraft", "X-Men", "Justice League",
    ],
  },
  {
    id: "muenchen",
    name: "München",
    special: true,
    words: [
      "Englischer Garten", "Marienplatz", "Frauenkirche", "Viktualienmarkt", "Eisbach",
      "Olympiapark", "Olympiaturm", "Allianz Arena", "Hofbräuhaus", "Wiesn",
      "FC Bayern", "TSV 1860", "BMW-Welt", "Deutsches Museum", "Tierpark Hellabrunn",
      "Isar", "Flaucher", "Chinesischer Turm", "Monopteros", "Schloss Nymphenburg",
      "Stachus", "Sendlinger Tor", "Odeonsplatz", "Glockenspiel", "Maximilianstraße",
      "Pinakothek", "Residenz", "Stammstrecke", "MVV", "Biergarten",
      "Weißwurstfrühstück", "Obatzda", "Leberkässemmel", "Radler", "Maß", "Auer Dult",
      "Tollwood", "Starkbierfest", "Schwabing", "Gärtnerplatz", "Glockenbachviertel",
      "Tegernsee", "Starnberger See", "Zugspitze", "Neuschwanstein", "LMU", "TUM",
      "Hochschule München", "Schickeria", "Grantler", "Servus",
    ],
  },
];

/** Standardmaessig aktiv: alle normalen Kategorien, Themen-Kategorien nicht. */
export const DEFAULT_CATEGORY_IDS = CATEGORIES.filter((c) => !c.special).map((c) => c.id);
